### ISSUE TITLE
Suggestion. Add lightning protection.

### ISSUE THREAD

**Issue by Ferbook3000** [Z0rdak/Yet-Another-World-Protector#103]
Lightning is currently able to create fire blocks. Even tough they cannot spread or cause any damage with the right flags, having to remove them manually is becoming quite annoying.

**Comment by Z0rdak** [comment]
With the next update (release sometime next week) the lightning flag will also prevent 
- lightning from striking down anywhere (not only entities)
- creating fire blocks
- deoxidize copper blocks

Note that these points may be separated into their own flags in the near future.
