### ISSUE TITLE
Players can still place liquids (water/lava) even when place-blocks flag is on

### ISSUE THREAD

**Issue by Ikethepro18** [Z0rdak/Yet-Another-World-Protector#104]
Just as described. Players still get the warning telling them that placing blocks is disabled, but the water/lava (and presumably any other non-vanilla liquids) still place

**Comment by Z0rdak** [comment]
Please state your
- Modloader + Modloader Version:
- YAWP Version:

**Comment by Ikethepro18** [comment]
Fabric 0.15.7
Minecraft 1.20.4
YAWP 0.0.2.9-beta3

**Comment by Z0rdak** [comment]
Thank you for providing this information.

The current fabric versions are still missing the flags 'scoop-liquid' and 'place-fluid'. See: [Wiki-Flags](https://github.com/Z0rdak/Yet-Another-World-Protector/wiki/Flags).
The place-blocks flag does not prevent this in the first place.

The message you are getting is a bug though and should not be show in this case.

**Comment by Z0rdak** [comment]
Quick update here:

I fixed the misleading error message AND added the two fluid related flags to fabric:  `scoop-liquid` and `place-fluid`.

This is part of version 0.0.4.1-beta1 and will be release within the next couple of days.
