### ISSUE TITLE
Using /wp dim to delete regions while they are children stops deleting of parent region

### ISSUE THREAD

**Issue by crimsonShard002** [Z0rdak/Yet-Another-World-Protector#107]
Mod Version: yawp-1.19.2-0.0.2.9-beta3-forge
Forge Version: 43.3.13

Issue:
Deleted Child regions through /wp dim. Went to delete parent region. Error: "Region [parent-region] can't be deleted because it has child regions." Attempt to remove child regions. Error: "Region [child-region] does not exist".

Workaround:
create identical region with same name, then remove child from parent.

**Comment by Z0rdak** [comment]
Thanks for the report. 
I’ve already fixed this issue in the upcoming update 0.0.4.0-beta1. 

Best regards
