### ISSUE TITLE
[1.16.5 Crash] Projectile or TNT indirectly griefs on behalf a dead entity throws null on Griefing Flag check

### ISSUE THREAD

**Issue by NighthowlerStudios** [Z0rdak/Yet-Another-World-Protector#116]
[crash-2024-06-22_19.21.48-server.txt](https://github.com/user-attachments/files/15937917/crash-2024-06-22_19.21.48-server.txt)

Requires Cracker's Wither Storm mod to get this specific one.

**Comment by NighthowlerStudios** [comment]
This might not be specific to Wither Storm, but it might actually crash if anything shoots a projectile that remains alive well after the entity dies.  It could affect the normal Wither as well.  Or even players who have ignited TNT

**Comment by Pixel1011** [comment]
Just had this exact thing occur to me in 1.18.2 after a ghast shot a fireball at me

crash report:


 
[crash-2024-06-24_19.07.58-server.txt](https://github.com/user-attachments/files/15960337/crash-2024-06-24_19.07.58-server.txt)

**Comment by Z0rdak** [comment]
Thank you both for your report.
I'll see to fix this asap.

**Comment by Z0rdak** [comment]
I just released a patch with version 0.0.4.0-beta2 to fix this issue.
Its already available on Modrinth and Curseforge.
