### ISSUE TITLE
Item frame and armor stand protection

### ISSUE THREAD

**Issue by Walrus98** [Z0rdak/Yet-Another-World-Protector#120]
I think that these blocks can be break despite the protection enabled

**Comment by Z0rdak** [comment]
Hey and thanks for opening the issue.

those things are technically not blocks, there are block entities and handled differently.

nevertheless they should be protected by the config. 

But without additional context of you Region setup, the YAWP version or the config I cannot help you further.

consider joining the discord server and get in tough with me there

best regards 
Zordak
