### ISSUE TITLE
1.18.2 Forge, YAWP Does not Launch: Single version must be surrounded by []: [40)

### ISSUE THREAD

**Issue by FoxyFox909** [Z0rdak/Yet-Another-World-Protector#123]
The mod does not launch on Forge, Minecraft version 1.18.2. Forge version seems to not matter.

Launching fails with message: `[17:03:01] [main/FATAL] [ne.mi.fo.la.MavenVersionAdapter/]: Failed to parse version spec [40)`

Logs from Minimum-Reproduction Instance (only YAWP installed):
[debug.log](https://github.com/user-attachments/files/16856097/debug.log)
[latest.log](https://github.com/user-attachments/files/16856099/latest.log)

Edit: Forgor an important thing... the mod version lmao. It is with the latest 1.18.2 mod version that this is happening, `yawp-1.18.2-0.0.4.0-beta2-forge`

**Comment by Z0rdak** [comment]
Resolved with 1.18.2-0.0.4.0-beta3

**Comment by FoxyFox909** [comment]
Can confirm it works on my end now. Thank you for the quick patch!
