### ISSUE TITLE
Can not go to the moon at Ad Astra mod

### ISSUE THREAD

**Issue by willis1030** [Z0rdak/Yet-Another-World-Protector#62]
Hi, do you play Ad Astra mod? I found that without YAWP I can normally go to the moon by rocket, but if there is YAWP on server side, rocket will go back to earth(overworld).
I don't know if this bug is on which mod?

**Comment by Z0rdak** [comment]
Hey! 
I haven't tested YAWP with Ad Astra yet. This sounds like an issue with flags which prevent dimensional travel, but I can't say for sure with this less information.

Please double-check if you are using flags which deny portal usage or traveling to other dimensions. These should be: `spawn-portal`, `enter-dim`, `use-portal`, `use-portal-players`. 
At best, disable **all** regions, Local or Dimensional and check if this problem still occurs.

Please further state your

- Forge Version: 
- YAWP Version:
- Ad Astra Version:

I'll look into how Ad Astra handles dimension travel with the rockets. 

Best regards.

**Comment by willis1030** [comment]
> 
Hi,
Now I have test some  command like this:
I create a new server, and go to the moon, failed. then I use this command:
/wp dim ad_astra:moon enable
it shows activated, then I launch the rocket, and landed on the moon success.
after that, I create another new server, try again, and type command:
/wp dim ad_astra:moon enable false
it shows deactivated, then I launch the rocket, and landed on the moon success.
Then I try 3rd time new server and type
/wp dim ad_astra:moon enable true
it success again.
I don't know how to try flags like enter-dim or others, but it seems solved my problem. I don't know why...

forge1.19.2-43.2.4
yawp-1.19.2-0.0.1.3-beta4
ad_astra-forge-1.19.2-1.12.3
(with
botarium-forge-1.19.2-1.8.2
resourcefulconfig-forge-1.19.2-1.0.17
resourcefullib-forge-1.19.2-1.1.19
needed)

now I must type the command for all dimensions as moon mars venus ...and other planets, include their orbits. I guess there should be another way to solve it.

**Comment by Z0rdak** [comment]
Thanks for the information. Glad you found a workaround.

Please try updating to the latest YAWP version 0.0.2.1-beta4 an try it again. 

Best regards

**Comment by willis1030** [comment]
hey, I do not notice there is a new version of yawp, now I tried it, and it's the same situation, if not type the command /wp dim ad_astra:moon enable , I can't enter the moon.

**Comment by Z0rdak** [comment]
Thanks for trying.

I think I found the issue. It seems to be an oversight on my side.

I'll try to fix it as soon as possible and publish a hotfix.

Best regards

**Comment by Z0rdak** [comment]
I just released a hotfix, which should fix the mentioned issue, for 1.16.5, 1.18.2 and 1.19.2. 
I am closing this issue. Feel free to get in touch if you have any further issues.

Best regards
