### ISSUE TITLE
Server Crash - 1.16.5 Forge 36.2.39

### ISSUE THREAD

**Issue by Foxydapirate12** [Z0rdak/Yet-Another-World-Protector#77]
Versions:
Forge: 36.2.39
Minecraft: 1.16.5
Mod Version: 1.16.5-0.0.2.8-beta1

Crash Report: https://gist.github.com/Foxydapirate12/568baad2bcb09d53c1f94c607a43e10a
Latest.log: https://gist.github.com/Foxydapirate12/3b0c22735be2b795e3c44be97dad92b1
Error String: _[net.minecraftforge.fml.config.ConfigTracker/CONFIG]: Detected config file conflict yawp-common.toml between yawp and yawp
[16Apr2023 04:10:22.441] [modloading-worker-12/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: yawp, class de.z0rdak.yawp.YetAnotherWorldProtector
java.lang.RuntimeException: Config conflict detected!_

I can provide any other details if need be ^^

**Comment by Z0rdak** [comment]
Well. That's embarrassing...
I am sorry about that. 

It seems I duplicated a line of code before building the jar which results in this error.

I'll replace this version on curseforge asap.

**Comment by Z0rdak** [comment]
Update version is up: https://www.curseforge.com/minecraft/mc-mods/yawp/files/4492754

If you have still issues feel free to open a new issue. :)

**Comment by Foxydapirate12** [comment]
Cheers ^^
