### ISSUE TITLE
Immersive Portals Compatibility

### ISSUE THREAD

**Issue by thesabinelim** [Z0rdak/Yet-Another-World-Protector#81]
It seems like with both YAWP and Immersive Portals installed, any portals created become standard portals rather than Immersive Portals. I'm guessing this is something to do with the spawn portal flag added by YAWP. I tested with the flag not set to anything and the flag set to disabled and in both instances I wasn't able to create Immersive Nether Portals. Issue was resolved as soon as I tried removing YAWP.

**Comment by Z0rdak** [comment]
Hey there, sorry about the late response. 

I'm looking into it and will try to make it compatible, but I can't promise anything.

Immersive Portals does some deep changes to the way Portals work. YAWP and Immersive Portals do touch some common code which may cause some code of Immersive Portals to be overridden or deactivate it.

Just to cite the mod page of Immersive Portals: 

> WARNING: This mod is incompatible with many mods, because this mod deeply change the inner working of the game. [Known compatibility issues](https://github.com/qouteall/ImmersivePortalsMod/labels/Mod%20Compatibility)

Best regards
