### ISSUE TITLE
Delete created region?

### ISSUE THREAD

**Issue by JavierMarinGuimera** [Z0rdak/Yet-Another-World-Protector#95]
How do I delete a created region?

**Comment by Z0rdak** [comment]
https://github.com/Z0rdak/Yet-Another-World-Protector/wiki/Commands#dimensional-regions

`/wp dim <dim> delete <regionname> [-y]` - will attempt to delete a region. Use -y to confirm the deletion of a region. Regions with children cannot be deleted at this point.
